# Site
#repository: sproogen/resume-theme
#repository: jycordero/resume-theme
favicon: images/favicon.ico

# Personal info
name: Joseph Y. Cordero Mercado
title: Ph.D. Research Assistant
email: joseph.cordero1@gmail.com
#website: www.github.com/jycordero/resume-theme
website: jycordero.github.io
resume: /images/Resume.pdf

# Social links
#twitter_username: faces
github_username:  jycordero
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: josephcordero3
linkedin_username: joseph-y-cordero-mercado-896ab58b
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | #This will include new lines to allow a paragraphs
  Hi, I am Joseph a Physics Ph.D. student in the field of Particle Physics. Along my development professionally and personally, I have placed myself in situations where I had to learn a significat portion of the skills on the go. I like to work in teams where I can validate or kill ideas fast and I am very open minded to constructive critism as I see it as an important aspect of fast growth. In the last 5 years I have had to be a physicist, engineer, programmer, machinist, plommer, laser operator, and others.

  Proficient in : <mark>Python</mark>, <mark>Bash</mark>

  Intermediate in: <mark>Bash Shell</mark>, <mark>C++</mark>, <mark>SQL</mark>, <mark>Statistics</mark>

  Basic in: <mark>HTML</mark> , <mark>PHP</mark>, <mark>Machine Learning</mark> 

# Jobs Section
# Jobs_title: Job Experience

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education
#
# Leadership Section
# leardership_title: Leadership Roles

# Awards Section
# awards_title: Awards

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Some of my other insterests are : 
    - Solving Jigsaw puzzles
    - Avid youtube consumer
      - Half as Interesting - General Knowledge
      - In a Nutshell - Science
      - 3Blue1Brown - Math
      - Marques Brownlee - Technoloy
      - Antonio Garcia Villaran - Art
    - Avid podcast listener
      - Freakonomics - Economics
      - Science Vs - Science
      - On Point - News
      - First Mondays - Supreme Court
      - Radiolab - Science
      - ReConsider - Political Science
    - Exploring new food
      - Tika Masala
      - Ramen
      - Lechon

# Footer
footer_show_references: true

# Build settings
#remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
